### ISSUE TITLE
`no-dom-traversal-in-connectedcallback` should be `no-child-traversal-in-connectedcallback`

### ISSUE THREAD

**Issue by koddsson** [github/eslint-plugin-custom-elements#21]
The _intent_ of the rule is to prevent errors from traversing children of an element which may not yet be rendered.

Traversing the DOM through global object like `document.body` or `document.querySelector` should be allowed as these elements will exist during the `connectedCallback` phase.

A somewhat concrete example of something needing to use global traversal would be an element which wants to be the only element on the page:

```js
class AriaAnnounceElement extends HTMLElement {

  connectedCallback() {
    // Only one active AriaAnnounce element can exist on the page.
    if (document.querySelectorAll(this.tagName).length > 1) {
      this.toggleAttribute('disabled', true)
    }
  }

}
```

**Comment by keithamus** [comment]
This project has now been merged with [eslint-plugin-wc](https://github.com/43081j/eslint-plugin-wc). Please head there for updates and maintenance.
