### ISSUE TITLE
`custom-elements/extends-correct-class` should check if the parent class extends `HTMLElement`

### ISSUE THREAD

**Issue by maicol07** [github/eslint-plugin-custom-elements#32]
Currently, `custom-elements/extends-correct-class` checks if the custom element extends HTMLElement. However, it triggers an error if the class I want to extend extends `HTMLElement`.

Example:

```javascript
class A extends HTMLElement {}

class B extends A {}

if (!window.customElements.get('custom-el')) {
  window.customElements.define('custom-el', B);
}
```

**Comment by keithamus** [comment]
Hey @maicol07 thanks for the issue!

I believe this would be too difficult to track properly with eslint, as tracking the inheritance chain project wide would get too complex too quickly. For example base class could sit across dependency boundaries. I would suggest inviting that much complexity into your codebase probably warrants turning this rule off.

If you have some ideas around how we can avoid such complexity I'd be open to suggestions. We could perhaps add a list of allowed classes that these elements can inherit from, as an option.

I'll close this issue for now, as in it's current form I don't think we can do much. If you disagree, or think there's a particular direction we should go in, I'd be happy to re-open it and investigate further.

**Comment by maicol07** [comment]
@keithamus the withelist option would be okay for my use case!

**Comment by keithamus** [comment]
Great! Would you like to work on a PR for this?

**Comment by maicol07** [comment]
Actually, I don't know how custom rules work 😅

However, I can look at it when I have time!

**Comment by mbullington** [comment]
I can try picking this up!

I've noticed many other rules rely on extending `HTMLElement` directly, too. Having a whitelist would be great for our use-cases.
